fastlane_version '2.157'
default_platform :ios

platform :ios do
  desc "Builds project and executes unit tests"
  lane :unit_test do |options|
    scan(
      scheme: "CD",
      device: "iPhone 15 Pro",  # Corrected this line
      clean: true,
      result_bundle: true,
      prelaunch_simulator: true,
      skip_package_dependencies_resolution: options[:skip_package_dependencies_resolution]
   )
  end
end
